[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000

fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
base = "${FORKING_RPC_URL_BASE}"

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config
